import Head from "next/head";
import CssBaseline from "@mui/material/CssBaseline";
import { useAuth } from "../hooks/auth";

import Nav from "./nav";
import LoginForm from "@/components/login-component";

export default function Home() {
  const { login, authError } = useAuth();
  return (
    <>
      <Head>
        <title>Khalig</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />

      <Nav />
      <LoginForm onLogin={login} authError={authError} />
    </>
  );
}
